import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Preset, PresetModel, PresetSection } from "../shared/types";

export const HOWTO_FILE = "HOW-TO-USE.md";

const COLUMNS: [string, (m: PresetModel) => string | undefined][] = [
  ["mode", (m) => m.modes?.join(", ")],
  ["duration", (m) => m.durations?.join(", ")],
  ["resolution", (m) => m.resolutions?.join(", ")],
  ["max inputs", (m) => m.max_inputs?.toString()],
];

/** max_inputs caps reference images for images and ingredients for video. */
const INPUT_LIMIT_LABEL = { image: "max references", video: "max ingredients" };

function sectionText(kind: "image" | "video", section: PresetSection): string {
  const columns = COLUMNS.filter(([, get]) => section.models.some((m) => get(m) !== undefined));
  const row = (cells: string[]) => `| ${cells.join(" | ")} |`;
  const lines = [
    `\`type: ${kind}\``,
    "",
    row(["model", ...columns.map(([name]) => (name === "max inputs" ? INPUT_LIMIT_LABEL[kind] : name))]),
    row(["---", ...columns.map(() => "---")]),
    ...section.models.map((m) => row([`\`${m.name}\``, ...columns.map(([, get]) => get(m) ?? "–")])),
    "",
  ];
  if (section.aspect_ratios) lines.push(`- aspect_ratio: ${section.aspect_ratios.map((a) => `"${a}"`).join(", ")}`);
  return lines.join("\n");
}

function presetText(preset: Preset): string {
  const parts = [`### \`tool: ${preset.tool}\` (${preset.name})`];
  if (preset.image) parts.push(sectionText("image", preset.image));
  if (preset.video) parts.push(sectionText("video", preset.video));
  if (preset.prompt_limit !== null) parts.push(`Prompts are limited to ${preset.prompt_limit} characters.`);
  if (preset.notes) parts.push(preset.notes);
  return parts.join("\n\n");
}

export function howToUse(presets: Preset[], waitUrl?: string): string {
  return `# Requesting images and video

<!-- Generated by Asset Prompter. Edits are overwritten. -->

In this project a human generates images and video by hand in an external tool. You request an asset by writing a prompt file into this folder; the human generates it and drops the results next to your prompt. You review every result first and either approve it or write the next version; the human gives the final approval, and can approve a result before you review it. The human's approval is final. Everything is plain files, and every path below is relative to this folder.

The work goes in rounds, at the human's pace:

1. You write every request you can in one go, tell the human in a line or two which slots are waiting, and end your turn.
2. The human generates them in the tool, maybe all at once, maybe over hours. Nothing arrives while you wait, so end your turn instead of polling the folder, sleeping, or checking back.
3. The human tells you when a batch is ready or approved${waitUrl ? " by pressing Notify agent, which wakes you (see Waiting for the human)" : ""}, or says "done" in the chat. One round can hold several slots; slots not mentioned are still with the human.
4. You review those results, write the next versions where needed, report briefly, and the next round starts.

## Layout

\`\`\`
<slot>/                one asset, e.g. hero-banner
  slot.md              what the asset is for
  v1.md                prompt and settings, version 1
  v1/                  the human's results for v1
    1.png  2.png
    selected.txt       name of the result the human chose; absent when there is only one
    info.md            written by the app: size, length and motion of each result, mismatches
    inputs.txt         written by the app: the files attached when generating
    1.frames/          video only: frame sheets, first-last.jpg, motion.jpg
  v1.review.md         your review of v1
  v1.feedback.md       the human's change request for v1, if any
  v2.md                the next attempt
  APPROVED             names the approved version, e.g. v2
  final.png            copy of the approved result; stays while the slot is reworked
  exports/             your variants of the final asset: crops, sizes, formats, edits
_trash/                deleted items; ignore
\`\`\`

A slot is one asset; a version is one attempt at it. A different asset gets its own slot.

Inside a slot you write only \`slot.md\`, \`vN.md\`, \`vN.review.md\` and files in \`exports/\`. Everything else there belongs to the human or the app. Once a slot has \`APPROVED\` it is Done: write only in its \`exports/\`. Only the human reopens it, by removing the approval; the app ignores a version written into a Done slot.

## Where things stand

The highest \`vN.md\` in a slot is its current version.

Check the rows in order; the first that matches decides.

| In the slot | Whose turn |
| --- | --- |
| \`APPROVED\` exists | Done. Use \`final.<ext>\`; its path stays the same if the human later approves another version. Leave the slot as it is, apart from variants in \`exports/\`. |
| current \`vN/\` has no results and a \`slot:\` input is not approved yet | Human: waiting for that slot; the app shows it as blocked |
| current \`vN/\` has no results | Human: generating |
| \`vN.feedback.md\` exists | You: write \`v<N+1>.md\` that makes the requested change |
| results, and no \`vN.review.md\` | You: review |
| a result in \`vN/\` was modified after \`vN.review.md\` | You: review again |
| \`vN.review.md\` says \`verdict: revise\` | You: write \`v<N+1>.md\` |
| \`vN.review.md\` says \`verdict: approve\` | Human: final approval |

When the human says they are done, generated something, or just "done", without naming a slot, go through every slot, act on each one where it is your turn, then list for the human what you did per slot.
${
  waitUrl
    ? `
## Waiting for the human

If you can run a command in the background and be woken when it ends, finish every turn by starting this, in the background, after your reply:

\`\`\`
curl -s ${waitUrl}
\`\`\`

It returns when the human presses Notify agent in the app, with a briefing: every slot where it is your turn, what to do, the human's words, and each result with its size and any mismatch; and every slot the human approved since the last briefing, with the file to use. Act on exactly those slots; do not scan the others, and do not re-read this file. An approved slot is final: write no review or version for it, and use its final file, or variants you make in \`exports/\`, wherever your work needs it. Open only the results, plus \`info.md\` where the briefing points to it. In the chat, report one short line per slot, since the details are in your reviews. Then start the command again. If it fails because the app is not running, do not retry: the human will tell you in the chat.
`
    : ""
}
## Requesting an asset

1. Pick a descriptive slot name that is not taken: lowercase letters, digits and hyphens. Create the folder.
2. Write \`slot.md\`: one or two sentences on where the asset appears and what it must achieve. The human judges results against this.
3. Write \`v1.md\`.
4. Tell the human which slots are waiting.

Request every asset you already know you need in one go, including ones that take another slot as input: the human generates a slot's inputs first.

## Version file

YAML frontmatter holds the settings the human selects in the tool. The body is the prompt, pasted into the tool verbatim. A second version of a video slot:

\`\`\`markdown
---
tool: google-flow
type: video
model: Veo 3.1 - Fast
mode: frames
aspect_ratio: "16:9"
duration: 8s
inputs:
  - role: start_frame
    slot: hero-image
changes: Slower push-in; in v1 the camera cut off the cafe sign.
---

Slow push-in toward the cafe entrance at dusk. Rain on the cobblestones, warm light in the windows. No people, no text.
\`\`\`

- \`tool\`, \`type\` (\`image\` or \`video\`) and \`model\` are required, spelled exactly as in Tools below.
- \`mode\` (video only): \`frames\` takes an optional \`start_frame\` and \`end_frame\` (with neither, the video comes from the prompt alone); \`ingredients\` takes one or more \`ingredient\` images.
- \`aspect_ratio\`, \`duration\`, \`resolution\`: set each one Tools lists for the chosen model; leave out the rest. How many results to generate is the human's choice; do not set it.
- \`inputs\`: files the human attaches. Each has a \`role\` (\`start_frame\`, \`end_frame\`, \`ingredient\` for video; \`reference\` for images) and either \`slot: <name>\`, meaning that slot's approved result or else its newest chosen one, or \`path: <file>\`.
- \`changes\`: from v2 on, one short sentence, around 20 words, on what changed and why. Longer reasoning goes in your review.
- \`params\`: optional map for any other setting the tool has.

The body is plain prompt text, complete on its own. The generator sees only this text and the attached inputs, with no memory of earlier versions or other slots.

Version files are immutable: to change anything, write the next version.

For image-to-video, use two slots: the image, then a video slot whose \`start_frame\` input is \`slot: <image slot>\`.

When one product or character appears in several assets, make a master slot for it first and give the others only that master as their reference for it; extra references of the same object pull its look in different directions. The app holds a slot back until every \`slot:\` input it uses is approved.

## Exports

When you make files from an approved asset, such as crops, other sizes, other formats or small edits, save them in \`<slot>/exports/\`, never over \`final.<ext>\` or anything in \`vN/\`. Name each so it says what it is, for example \`hero-1920x1080.webp\`, \`hero-square-crop.png\` or \`logo-32.png\`. The human sees them with the final asset and copies them from there. Images and videos the browser can show appear there, including \`.svg\` and \`.ico\`.

## Reviewing a result

Every result comes to you first; the human's comment is optional.

1. Read \`vN/info.md\`: which inputs were attached (one marked "NOT approved yet" was a draft, so compare against what was approved since), each result's size and length, and anything that does not match \`vN.md\`, such as a 10 s clip when you asked for 8 s. A mismatch almost always means the human chose a different model or setting in the tool, not that the tool cannot do it: name the setting to change in your review and keep the request as it is. Accept the result only if it still does what \`slot.md\` asks, and say so.
2. Open the results. If \`vN/selected.txt\` exists, the human chose that one and the others were passed over; otherwise judge them all and pick the best. For a video, view every sheet in \`vN/<file>.frames/\` in order: one sheet per second, four frames 250 ms apart, left to right, top to bottom. Then look at \`first-last.jpg\` (does it loop?) and \`motion.jpg\` (red is what changed during the clip), and read the motion numbers in \`info.md\`: they show slow changes, such as the light shifting, that stills hide. If there are no sheets, ask the human to describe the video. You cannot hear sound; if it matters, ask the human to check it.
3. If \`vN.feedback.md\` exists, it is a change request: the human did not accept this result. Look at the result and the prompt that made it, then write \`v<N+1>.md\` with a new complete prompt that gets what they asked for, and \`vN.review.md\` with \`verdict: revise\`. Do everything the request asks, then add your own fixes on top.
4. Judge the result against \`slot.md\` and the prompt, and write \`vN.review.md\`:

\`\`\`markdown
---
verdict: approve
pick: 2.jpg
---

The sky stays at blue hour and the camera is still, so the headline area stays calm. Check the sound: it should be quiet rain with no music.
\`\`\`

- \`verdict\`: \`approve\` when the result does what \`slot.md\` asks, or \`revise\` when it needs another attempt, in which case you also write \`v<N+1>.md\` in the same turn.
- \`pick\`: the result you recommend, only when \`vN/\` holds more than one and there is no \`vN/selected.txt\`. Leave it out otherwise; with one result, or after the human chose, it means nothing.
- The body: a few sentences for the human on what works, what does not, and what they should check that you cannot, such as sound.

Your approval is a recommendation: the human confirms it, comments, or approves something else. When you answer a comment, rewrite \`vN.review.md\`.

## Tools

${presets.map(presetText).join("\n\n") || "No tool presets are installed. Ask the human which tool and settings to use."}
`;
}

export function writeHowTo(projectDir: string, presets: Preset[], waitUrl?: string): void {
  const path = join(projectDir, HOWTO_FILE);
  const content = howToUse(presets, waitUrl);
  if (existsSync(path) && readFileSync(path, "utf8") === content) return;
  writeFileSync(path, content);
}
