import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import YAML from "yaml";
import type { Preset, PresetSection } from "../shared/types";

export const HOWTO_FILE = "HOW-TO-USE.md";

function sectionText(kind: "image" | "video", section: PresetSection): string {
  const lines = [`**${kind}**`, ""];
  for (const m of section.models) {
    const bits = [
      m.modes && `modes: ${m.modes.join(", ")}`,
      m.durations && `durations: ${m.durations.join(", ")}`,
      m.resolutions && `resolutions: ${m.resolutions.join(", ")}`,
      m.max_inputs !== undefined && `max inputs: ${m.max_inputs}`,
    ].filter(Boolean);
    lines.push(`- model \`${m.name}\`${bits.length ? ` (${bits.join("; ")})` : ""}`);
  }
  if (section.aspect_ratios) lines.push(`- aspect_ratio: ${section.aspect_ratios.map((a) => `"${a}"`).join(", ")}`);
  if (section.outputs) lines.push(`- outputs: ${section.outputs.join(", ")}`);
  return lines.join("\n");
}

function presetText(preset: Preset): string {
  const parts = [`### \`tool: ${preset.tool}\` (${preset.name})`];
  if (preset.image) parts.push(sectionText("image", preset.image));
  if (preset.video) parts.push(sectionText("video", preset.video));
  if (preset.prompt_limit !== null) parts.push(`Prompt limit: ${preset.prompt_limit} characters.`);
  if (preset.notes) parts.push(preset.notes);
  return parts.join("\n\n");
}

const example = YAML.stringify({
  tool: "google-flow",
  type: "video",
  model: "Veo 3.1 - Fast",
  mode: "frames",
  aspect_ratio: "16:9",
  outputs: 2,
  duration: "8s",
  inputs: [
    { role: "start_frame", slot: "hero-image" },
    { role: "end_frame", path: "references/logo.png" },
  ],
  changes: "Slower camera move; v1 cut off the subject's head.",
}).trimEnd();

export function howToUse(presets: Preset[]): string {
  return `# How to request assets in this project

<!-- Generated by Asset Prompter. Edits are overwritten. -->

You cannot generate images or video yourself. A human does it by hand in an external tool. This folder is how you ask for an asset and get it back. You write prompt files; the human generates the asset and drops it next to your prompt. Everything is plain files: there is no API and no index to update.

## Layout

\`\`\`
<this folder>/
  HOW-TO-USE.md
  <slot>/                 one asset you need, e.g. hero-banner
    slot.md               what the asset is for (you write this once)
    v1.md                 your prompt and settings for version 1
    v1/                   the human's results for v1
      1.png  2.png        candidates
      selected.txt        file name of the chosen candidate (absent when there is one)
      1.frames/001.jpg    for videos: one 2x2 sheet per second, frames 250 ms apart
    v1.feedback.md        the human's comment on v1
    v2.md                 your revised prompt
    APPROVED              present once the human approves; contains the version, e.g. v2
    final.png             copy of the approved asset; use this path in your work
\`\`\`

A slot is one asset. Versions are attempts at that asset. Use a second slot for a different asset, not a new version.

## Asking for an asset

1. Pick a slot name: lowercase letters, digits and hyphens (\`hero-banner\`). Create the folder.
2. Write \`slot.md\`: one or two sentences on where the asset is used and what it must achieve. The human reads it to judge results against the purpose, not only against your prompt.
3. Write \`v1.md\` (format below).
4. Tell the human the slot is waiting. You are done until they come back.

Create only \`slot.md\` and \`vN.md\` files. Never write into \`vN/\`, and never create or edit \`APPROVED\`, \`final.*\`, \`selected.txt\` or \`*.feedback.md\`: those belong to the human.

## Version file

Frontmatter holds the settings the human has to click in the tool. The body is the prompt, copied verbatim into the tool, so it must contain the prompt and nothing else: no headings, no commentary, no markdown formatting.

\`\`\`markdown
---
${example}
---

The prompt text, exactly as it should be pasted into the generator.
\`\`\`

- \`tool\`, \`type\` (\`image\` or \`video\`) and \`model\` are required. Use the exact values listed under "Tools" below.
- \`mode\`, \`duration\` and \`resolution\` are video settings. Leave out any setting that does not apply.
- \`inputs\` lists files the human must attach. Each has a \`role\` and either \`slot\` (the chosen asset of another slot in this project) or \`path\` (a file path relative to this folder). Roles: \`start_frame\`, \`end_frame\`, \`ingredient\` for video; \`reference\` for images.
- \`changes\` is required from v2 on: one sentence on what you changed and why. Leave it out of v1.
- \`params\` is an optional map for any setting not covered above.

For image-to-video, make two slots: the image first, then a video slot whose input points at the image slot. Each then has its own history.

## Reviewing a result

When the human says a version is generated:

1. List the slot folder. The highest \`vN.md\` is the current version.
2. Find the result in \`vN/\`. If \`selected.txt\` exists it names the chosen file; otherwise there is a single file. Look at the image. For a video, look at the sheets in \`<file>.frames/\` in order.
3. Read \`vN.feedback.md\` if it exists. The human's comment outranks your own opinion of the result.
4. If it needs another attempt, write the next version file: list the folder, take the highest number, add one. Write the full prompt again, not a diff. Never edit or overwrite an existing version file.
5. If it is good, say so. The human approves it, and \`final.<ext>\` appears in the slot.

## Tools

${presets.map(presetText).join("\n\n") || "No tool presets are installed. Ask the human which tool and settings to use."}
`;
}

export function writeHowTo(projectDir: string, presets: Preset[]): void {
  const path = join(projectDir, HOWTO_FILE);
  const content = howToUse(presets);
  if (existsSync(path) && readFileSync(path, "utf8") === content) return;
  writeFileSync(path, content);
}
