import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Preset, PresetModel, PresetSection } from "../shared/types";

export const HOWTO_FILE = "HOW-TO-USE.md";

const COLUMNS: [string, (m: PresetModel) => string | undefined][] = [
  ["mode", (m) => m.modes?.join(", ")],
  ["duration", (m) => m.durations?.join(", ")],
  ["resolution", (m) => m.resolutions?.join(", ")],
  ["max inputs", (m) => m.max_inputs?.toString()],
];

/** max_inputs caps reference images for images and ingredients for video. */
const INPUT_LIMIT_LABEL = { image: "max references", video: "max ingredients" };

function sectionText(kind: "image" | "video", section: PresetSection): string {
  const columns = COLUMNS.filter(([, get]) => section.models.some((m) => get(m) !== undefined));
  const row = (cells: string[]) => `| ${cells.join(" | ")} |`;
  const lines = [
    `\`type: ${kind}\``,
    "",
    row(["model", ...columns.map(([name]) => (name === "max inputs" ? INPUT_LIMIT_LABEL[kind] : name))]),
    row(["---", ...columns.map(() => "---")]),
    ...section.models.map((m) => row([`\`${m.name}\``, ...columns.map(([, get]) => get(m) ?? "–")])),
    "",
  ];
  if (section.aspect_ratios) lines.push(`- aspect_ratio: ${section.aspect_ratios.map((a) => `"${a}"`).join(", ")}`);
  if (section.outputs) lines.push(`- outputs: ${section.outputs.join(", ")}`);
  return lines.join("\n");
}

function presetText(preset: Preset): string {
  const parts = [`### \`tool: ${preset.tool}\` (${preset.name})`];
  if (preset.image) parts.push(sectionText("image", preset.image));
  if (preset.video) parts.push(sectionText("video", preset.video));
  if (preset.prompt_limit !== null) parts.push(`Prompts are limited to ${preset.prompt_limit} characters.`);
  if (preset.notes) parts.push(preset.notes);
  return parts.join("\n\n");
}

export function howToUse(presets: Preset[]): string {
  return `# Requesting images and video

<!-- Generated by Asset Prompter. Edits are overwritten. -->

In this project a human generates images and video by hand in an external tool. You request an asset by writing a prompt file into this folder; the human generates it and drops the results next to your prompt. Everything is plain files, and every path below is relative to this folder.

## Layout

\`\`\`
<slot>/                one asset, e.g. hero-banner
  slot.md              what the asset is for
  v1.md                prompt and settings, version 1
  v1/                  the human's results for v1
    1.png  2.png
    selected.txt       name of the chosen result; absent when there is only one
    1.frames/          video only: frame sheets
  v1.feedback.md       the human's comment on v1
  v2.md                the next attempt
  APPROVED             names the approved version, e.g. v2
  final.png            copy of the approved result
_trash/                deleted items; ignore
\`\`\`

A slot is one asset; a version is one attempt at it. A different asset gets its own slot.

Inside a slot you write only \`slot.md\` and \`vN.md\`. Everything else there belongs to the human.

## Where things stand

The highest \`vN.md\` in a slot is its current version.

| In the slot | Whose turn |
| --- | --- |
| \`APPROVED\` was modified after the current \`vN.md\` | Done. Use \`final.<ext>\`; its path stays the same if the human later approves another version. |
| current \`vN/\` has no results | Human: generating |
| results, no \`vN.feedback.md\` | Human: reviewing |
| \`vN.feedback.md\` exists | You: review and revise |

## Requesting an asset

1. Pick a descriptive slot name that is not taken: lowercase letters, digits and hyphens. Create the folder.
2. Write \`slot.md\`: one or two sentences on where the asset appears and what it must achieve. The human judges results against this.
3. Write \`v1.md\`.
4. Tell the human which slots are waiting.

Request every asset you already know you need in one go, including ones that take another slot as input: the human generates a slot's inputs first.

## Version file

YAML frontmatter holds the settings the human selects in the tool. The body is the prompt, pasted into the tool verbatim. A second version of a video slot:

\`\`\`markdown
---
tool: google-flow
type: video
model: Veo 3.1 - Fast
mode: frames
aspect_ratio: "16:9"
outputs: 2
duration: 8s
inputs:
  - role: start_frame
    slot: hero-image
changes: Slower push-in; in v1 the camera cut off the cafe sign.
---

Slow push-in toward the cafe entrance at dusk. Rain on the cobblestones, warm light in the windows. No people, no text.
\`\`\`

- \`tool\`, \`type\` (\`image\` or \`video\`) and \`model\` are required, spelled exactly as in Tools below.
- \`mode\` (video only): \`text\` takes no inputs; \`frames\` takes a \`start_frame\` and optionally an \`end_frame\`; \`ingredients\` takes one or more \`ingredient\` images.
- \`aspect_ratio\`, \`outputs\`, \`duration\`, \`resolution\`: set each one Tools lists for the chosen model; leave out the rest. \`outputs\` is how many results the human generates; ask for more while exploring a look, fewer once it is settled.
- \`inputs\`: files the human attaches. Each has a \`role\` (\`start_frame\`, \`end_frame\`, \`ingredient\` for video; \`reference\` for images) and either \`slot: <name>\`, meaning that slot's approved result or else its newest chosen one, or \`path: <file>\`.
- \`changes\`: from v2 on, one sentence on what changed and why.
- \`params\`: optional map for any other setting the tool has.

The body is plain prompt text, complete on its own. The generator sees only this text and the attached inputs, with no memory of earlier versions or other slots.

Version files are immutable: to change anything, write the next version.

For image-to-video, use two slots: the image, then a video slot whose \`start_frame\` input is \`slot: <image slot>\`.

## Reviewing a result

When the human says a version is ready:

1. Open the chosen result of the current version: the file named in \`vN/selected.txt\`, or the only file in \`vN/\`. For a video, view every sheet in \`vN/<file>.frames/\` in order: one sheet per second of video, four frames 250 ms apart, left to right, top to bottom. If there are no sheets, ask the human to describe the video.
2. Read \`vN.feedback.md\` if it exists. It is about the chosen result; the other files in \`vN/\` are ones the human passed over. Fix everything the comment raises, then add your own fixes on top.
3. Judge the result against \`slot.md\` and the prompt, then either write \`v<N+1>.md\` with a complete new prompt and \`changes\`, or tell the human it is ready to approve.

## Tools

${presets.map(presetText).join("\n\n") || "No tool presets are installed. Ask the human which tool and settings to use."}
`;
}

export function writeHowTo(projectDir: string, presets: Preset[]): void {
  const path = join(projectDir, HOWTO_FILE);
  const content = howToUse(presets);
  if (existsSync(path) && readFileSync(path, "utf8") === content) return;
  writeFileSync(path, content);
}
