import { register } from "./i18n";

/**
 * Serbian. The key is the English text as it appears in the code; the value is the Serbian. A key that is not
 * here is shown in English. The text speaks to the reader as "ti" and avoids past-tense forms that would show
 * the reader's gender. Terms it keeps: prompt, slot, preset, klip, frejm, aset, fajl, folder, agent.
 * Tokens such as {status:…} and {button:…} are read by the tutorial and must stay exactly as in the English.
 */
const SR: Record<string, string> = {
  // ---- labels used in several places (STATUS_LABEL, ROLE_LABEL, TRASH_KIND, view widths, tags) ----
  "Waiting for input": "Čeka ulaz",
  "Needs generating": "Treba generisati",
  "Agent's turn": "Na agentu",
  "Needs your approval": "Čeka tvoje odobrenje",
  Approved: "Odobreno",
  "No prompt yet": "Još nema prompta",
  "Start frame": "Početni frejm",
  "End frame": "Krajnji frejm",
  Ingredient: "Sastojak",
  Reference: "Referenca",
  Keyframe: "Ključni frejm",
  Video: "Video",
  Audio: "Audio",
  Source: "Izvor",
  Project: "Projekat",
  Slot: "Slot",
  Result: "Rezultat",
  File: "Fajl",
  Normal: "Normalno",
  Wide: "Široko",
  Full: "Puna širina",
  Language: "Jezik",

  // ---- Dialogs ----
  Close: "Zatvori",
  "Close (Esc)": "Zatvori (Esc)",
  Remove: "Ukloni",
  Delete: "Obriši",
  "Delete {name}": "Obriši {name}",
  "The project leaves this list. Its folder stays where it is, with every prompt and result:": "Projekat nestaje sa ove liste. Njegov folder ostaje gde jeste, sa svim promptovima i rezultatima:",
  "The project folder, with every slot, prompt and result, moves to": "Folder projekta, sa svim slotovima, promptovima i rezultatima, seli se u",
  "Delete it there for good when you are sure.": "Tamo ga obriši zauvek kad budeš siguran.",
  "The agent waiting on it is told to stop.": "Agentu koji čeka na njemu biće rečeno da stane.",
  "Remove from the list": "Ukloni sa liste",
  "Delete project": "Obriši projekat",
  "You can undo it right after.": "Odmah posle možeš da poništiš.",
  "Nothing in _trash.": "U _trash nema ničega.",
  "Result of {slot} v{version}": "Rezultat slota {slot} v{version}",
  "deleted {when}": "obrisano {when}",
  Restore: "Vrati",
  "Open the _trash folder": "Otvori folder _trash",
  "To delete for good, empty the folder by hand.": "Da obrišeš zauvek, isprazni folder ručno.",
  Prompt: "Prompt",
  "Copy prompt": "Kopiraj prompt",
  "{n} characters": "{n} znakova",
  "{n}s": "{n} s",
  "Agent's pick": "Izbor agenta",
  Selected: "Izabrano",
  "All results": "Svi rezultati",
  selected: "izabrano",
  "the agent's pick": "izbor agenta",
  "showing now": "sada na ekranu",
  Previous: "Prethodni",
  "Previous (Left arrow)": "Prethodni (strelica levo)",
  Next: "Sledeći",
  "Next (Right arrow)": "Sledeći (strelica desno)",
  "Your pick. Click to take it back.": "Tvoj izbor. Klikni da ga povučeš.",
  "The agent's pick. Click to make it yours.": "Izbor agenta. Klikni da bude tvoj.",
  "Select this result": "Izaberi ovaj rezultat",
  Select: "Izaberi",
  "Copy image": "Kopiraj sliku",
  "Not set": "Nije zadato",
  Tool: "Alat",
  Type: "Tip",
  Image: "Slika",
  Model: "Model",
  Mode: "Režim",
  "Aspect ratio": "Odnos stranica",
  Length: "Trajanje",
  Resolution: "Rezolucija",
  "What changed": "Šta je promenjeno",
  "One sentence on what this version changes and why": "Jedna rečenica o tome šta ova verzija menja i zašto",
  "New slot": "Novi slot",
  "Slot name": "Ime slota",
  "This becomes the folder name, for example hero-banner.": "Ovo postaje ime foldera, na primer hero-banner.",
  "What is this asset for": "Čemu služi ovaj aset",
  "Create slot": "Napravi slot",
  "New version": "Nova verzija",
  "The input file of v{version} is carried over.": "Ulazni fajl verzije v{version} se prenosi.",
  "The {n} input files of v{version} are carried over.": "Ulazni fajlovi verzije v{version} ({n}) se prenose.",
  "Save v{n}": "Sačuvaj v{n}",
  Clone: "Kloniraj",
  "Name of the copy": "Ime kopije",
  "The whole slot is copied: prompts, results, reviews and approval. The original stays as it is.": "Kopira se ceo slot: promptovi, rezultati, recenzije i odobrenje. Original ostaje kakav jeste.",
  "The copy is not approved, so you can ask for changes on it right away": "Kopija nije odobrena, pa odmah možeš da tražiš izmene na njoj",
  "Clone and remove approval": "Kloniraj i ukloni odobrenje",
  "Add a project": "Dodaj projekat",
  "New project": "Novi projekat",
  "Existing folder": "Postojeći folder",
  "Project name": "Ime projekta",
  "Created as a folder in {dir}": "Pravi se kao folder u {dir}",
  "Full path of the folder": "Puna putanja foldera",
  "Use this for a folder inside a repo your agent works in. Slots are created directly in it.": "Za folder unutar repozitorijuma u kom tvoj agent radi. Slotovi se prave direktno u njemu.",
  "Create project": "Napravi projekat",
  "Add folder": "Dodaj folder",

  // ---- Done ----
  "{n} variant of the final asset": "{n} varijanta finalnog aseta",
  "{n} variants of the final asset": "{n} varijanti finalnog aseta",
  Variant: "Varijanta",
  "View {file}": "Pogledaj {file}",
  "Image copied": "Slika kopirana",
  "Path copied": "Putanja kopirana",
  "Copy path": "Kopiraj putanju",
  "View {name}, approved version {n}": "Pogledaj {name}, odobrena verzija {n}",
  "No file": "Nema fajla",
  "Approved version {n}": "Odobrena verzija {n}",
  "{name}: click to copy": "{name}: klikni da kopiraš",
  'Slot name "{name}" copied to the clipboard': "Ime slota „{name}” je kopirano",
  Details: "Detalji",
  "Details {name}": "Detalji: {name}",
  "All done slots": "Svi završeni slotovi",
  "#{number} {name}, showing now": "#{number} {name}, sada na ekranu",
  "#{number} {name}": "#{number} {name}",

  // ---- ProjectMenu ----
  "Project: {name}. Switch project": "Projekat: {name}. Promeni projekat",
  "Choose a project": "Izaberi projekat",
  "None yet": "Još nijedan",
  "An agent is waiting on this project": "Agent čeka na ovom projektu",
  Projects: "Projekti",
  "{n} waiting for you": "{n} čeka na tebe",
  "agent waiting": "agent čeka",
  "Deleted projects": "Obrisani projekti",
  "Remove {name} from the list": "Ukloni {name} sa liste",

  // ---- SlotCard ----
  "Approved.": "Odobreno.",
  "You asked: {text}": "Tvoj zahtev: {text}",
  "Agent: {text}": "Agent: {text}",
  "No change request": "Bez zahteva za izmenu",
  "Never generated": "Nikad generisano",
  Expand: "Raširi",
  Collapse: "Sklopi",
  "{n} version in this slot": "{n} verzija u ovom slotu",
  "{n} versions in this slot": "Verzija u ovom slotu: {n}",
  "Generate it after {names} is approved": "Generiši ga kad {names} bude odobren",
  "Waiting for {names}": "Čeka na {names}",
  "Name to check": "Proveri ime",
  "Slot path copied": "Putanja slota kopirana",
  'Slot "{name}" moved to _trash': "Slot „{name}” je premešten u _trash",
  'Slot "{name}" is back': "Slot „{name}” je vraćen",
  "Move to _trash": "Premesti u _trash",
  Keep: "Zadrži",
  'This slot has no version file yet. The agent writes v1.md here, or add one with "New version".': "Ovaj slot još nema fajl verzije. Agent ovde piše v1.md, ili ga dodaj preko „Nova verzija”.",

  // ---- Tutorial ----
  "The idea": "Ideja",
  "Your agent plans, you generate": "Tvoj agent planira, ti generišeš",
  "Your agent works in files, so Asset Prompter turns image and video generation into files too. The agent writes what it needs, you make it in the generator you like, and everything comes back to a folder the agent can read.":
    "Tvoj agent radi sa fajlovima, pa Asset Prompter i generisanje slika i videa pretvara u fajlove. Agent napiše šta mu treba, ti to napraviš u generatoru koji voliš, i sve se vraća u folder koji agent može da čita.",
  "Each side does what it is best at: the agent plans and checks, you generate and decide.": "Svaka strana radi ono u čemu je najbolja: agent planira i proverava, ti generišeš i odlučuješ.",
  "No MCP server or API key is needed. Use any generator at its own price.": "Ne treba ni MCP server ni API ključ. Koristi bilo koji generator po njegovoj ceni.",
  "Your approval is final, so nothing reaches the project without you.": "Tvoje odobrenje je konačno, pa ništa ne stiže u projekat bez tebe.",
  Welcome: "Dobro došao",
  "You and your agent, one shared folder": "Ti i tvoj agent, jedan zajednički folder",
  "Your AI agent knows which images and videos it needs. You are the one who can generate them. Asset Prompter is the hand-off between you two, and nothing is final until you approve it.":
    "Tvoj AI agent zna koje mu slike i video trebaju. Ti si taj koji može da ih generiše. Asset Prompter je primopredaja između vas dvoje, i ništa nije konačno dok ti ne odobriš.",
  "The pictures use Google Flow as the generator, but it works the same with any image or video app you generate in.": "Na slikama je Google Flow kao generator, ali isto radi sa bilo kojom aplikacijom za slike ili video u kojoj generišeš.",
  "The agent's review is optional. Approve a result yourself and it goes straight to Done; ask the agent only when you want its opinion.": "Recenzija agenta nije obavezna. Odobri rezultat sam i ide pravo u Završeno; pitaj agenta samo kad želiš njegovo mišljenje.",
  "This tour takes about two minutes. Use the buttons below or the arrow keys.": "Ovaj vodič traje oko dva minuta. Koristi dugmad ispod ili strelice na tastaturi.",
  "Everything is plain files in a folder. There is no account and no database.": "Sve su obični fajlovi u folderu. Nema naloga ni baze podataka.",
  "You can open it again any time with the Tutorial button in the top bar.": "Možeš ga otvoriti ponovo bilo kad dugmetom Vodič u gornjoj traci.",
  "Start with a project": "Počni od projekta",
  "A project is just a folder. Each one holds the assets for one piece of work, such as a website or a campaign.": "Projekat je samo folder. Svaki drži asete za jedan posao, na primer sajt ili kampanju.",
  "The project you are in. Click it to switch to another one.": "Projekat u kom si. Klikni da pređeš na drugi.",
  "The number counts the slots that wait for you in that project.": "Broj pokazuje koliko slotova čeka na tebe u tom projektu.",
  "Add a project: make a new one, or point at a folder inside the repo your agent works in.": "Dodaj projekat: napravi nov, ili pokaži na folder unutar repozitorijuma u kom tvoj agent radi.",
  "Your agent": "Tvoj agent",
  "Bring in your agent": "Dovedi svog agenta",
  "A new project starts empty. One message is all your agent needs to learn how the folder works.": "Nov projekat počinje prazan. Jedna poruka je sve što je tvom agentu potrebno da nauči kako folder radi.",
  "Press Copy agent instructions and paste it into a new chat with your agent. It starts writing prompts into the project.": "Pritisni Kopiraj uputstvo za agenta i nalepi ga u nov razgovor sa agentom. On počinje da piše promptove u projekat.",
  "The same button is always in the top bar. View shows what gets copied.": "Isto dugme je uvek u gornjoj traci. Prikaži pokazuje šta se kopira.",
  "No agent at hand? New slot lets you write a prompt yourself.": "Nemaš agenta pri ruci? Novi slot ti daje da sam napišeš prompt.",
  "The feed": "Feed",
  "Every asset is a slot": "Svaki aset je slot",
  "Each card is one slot: one image or video the agent asked for. Its status tag tells you whose turn it is.": "Svaka kartica je jedan slot: jedna slika ili video koji je agent tražio. Oznaka statusa kaže ko je na potezu.",
  "In progress holds the open slots. Approved ones move to Done.": "U toku drži otvorene slotove. Odobreni prelaze u Završeno.",
  "Filter by status. {status:waiting_generation} and {status:waiting_review} are your turn. {status:waiting_input} means the slot is built from another slot's image and waits until that one is approved.":
    "Filtriraj po statusu. {status:waiting_generation} i {status:waiting_review} su tvoj potez. {status:waiting_input} znači da slot nastaje iz slike drugog slota i čeka da taj bude odobren.",
  "The tag on a card shows the step the slot is at now, and whose turn it is.": "Oznaka na kartici pokazuje na kom je koraku slot sada i ko je na potezu.",
  "Write a new version yourself, clone the slot, or delete it. Deleted slots go to _trash.": "Napiši sam novu verziju, kloniraj slot ili ga obriši. Obrisani slotovi idu u _trash.",
  Generate: "Generiši",
  "Generate it, then drop it back": "Generiši, pa vrati rezultat",
  "A slot marked {status:waiting_generation} waits for you. Open the tool you generate with, such as Google Flow, and work through the card from top to bottom.":
    "Slot sa oznakom {status:waiting_generation} čeka na tebe. Otvori alat u kom generišeš, na primer Google Flow, i prođi karticu od vrha do dna.",
  "In the tool, choose these settings first: image or video, the aspect ratio and the model.": "U alatu prvo izaberi ova podešavanja: slika ili video, odnos stranica i model.",
  "Press {button:Copy prompt} and paste it into the tool's prompt box. The button turns green, so you can see which prompts you already copied.":
    "Pritisni {button:Copy prompt} i nalepi ga u polje za prompt u alatu. Dugme pozeleni, pa vidiš koje promptove si već kopirao.",
  "Add the reference images the card lists to the tool: press Copy image and paste it there, or drag the picture onto the tool's upload area.":
    "Dodaj u alat referentne slike koje kartica navodi: pritisni Kopiraj sliku i nalepi je tamo, ili prevuci sliku na polje za upload.",
  "Drop the result here or choose the file. Images can also be pasted with Ctrl+V. Several results are fine.": "Spusti rezultat ovde ili izaberi fajl. Slike možeš i da nalepiš sa Ctrl+V. Više rezultata je u redu.",
  "Hand over": "Predaj",
  "Hand it to the agent": "Predaj agentu",
  "The agent can check each result against what it asked for. Already happy with one? Approve it yourself and skip this step.": "Agent može da uporedi svaki rezultat sa onim što je tražio. Već ti se neki sviđa? Odobri ga sam i preskoči ovaj korak.",
  "Your result sits in the card. The app checks its size and length against the settings.": "Tvoj rezultat stoji u kartici. Aplikacija proverava njegovu veličinu i trajanje prema podešavanjima.",
  "The slot now says {status:waiting_agent}.": "Slot sada kaže {status:waiting_agent}.",
  'Press {button:Notify agent} when your batch is in. It also tells the agent what you approved. A green dot means the agent is listening, and {button:Stop} beside it ends that; if it is not listening, tell it "done" in the chat.':
    "Pritisni {button:Notify agent} kad je tvoja tura gotova. To agentu javlja i šta si odobrio. Zelena tačka znači da agent sluša, a {button:Stop} pored nje to prekida; ako ne sluša, napiši mu „gotovo” u razgovoru.",
  Approve: "Odobri",
  "Read the review, then approve": "Pročitaj recenziju, pa odobri",
  "The agent approves a result or asks for another try. Its approval is a recommendation. Yours is the one that counts.": "Agent odobrava rezultat ili traži još jedan pokušaj. Njegovo odobrenje je preporuka. Tvoje je ono koje se računa.",
  "Click the chip to read what the agent thinks of the result.": "Klikni na oznaku da pročitaš šta agent misli o rezultatu.",
  "With several results the agent picks one (purple check). Click another thumbnail to pick it yourself (green). Click your pick again to take it back.":
    "Kad ima više rezultata, agent bira jedan (ljubičasta kvačica). Klikni drugu sličicu da sam izabereš (zelena). Klikni svoj izbor ponovo da ga povučeš.",
  "Approve makes this version final and moves the slot to Done. From then on the agent leaves it alone.": "Odobri čini ovu verziju konačnom i prebacuje slot u Završeno. Od tada ga agent ne dira.",
  "Change requests": "Zahtevi za izmenu",
  "Not right yet? Ask for changes": "Nije još to? Traži izmene",
  "You never rewrite a prompt yourself. Say what should change, and the agent writes the next version: a new prompt that asks for that change. You generate it like the first one.":
    "Nikad sam ne prepravljaš prompt. Kaži šta treba da se promeni, a agent piše sledeću verziju: nov prompt koji traži tu promenu. Generišeš je kao i prvu.",
  "{button:Request changes} opens a note for the agent. It saves when you click away. Then press {button:Notify agent}: the agent writes v2, and the slot comes back to you as {status:waiting_generation}.":
    "{button:Request changes} otvara poruku za agenta. Čuva se kad klikneš van nje. Zatim pritisni {button:Notify agent}: agent piše v2, a slot ti se vraća kao {status:waiting_generation}.",
  "Earlier versions stay folded under the card, with what you asked for.": "Ranije verzije ostaju sklopljene ispod kartice, zajedno sa onim što si tražio.",
  Compare: "Uporedi",
  "Compare results full size": "Uporedi rezultate u punoj veličini",
  "Click any image to open the viewer. It holds every result of the slot, across all its versions.": "Klikni bilo koju sliku da otvoriš pregledač. U njemu je svaki rezultat slota, kroz sve verzije.",
  "Every result is in the strip. The white frame is the one on screen; the check marks the pick, green for yours and purple for the agent's.":
    "Svaki rezultat je u traci. Beli okvir je onaj na ekranu; kvačica označava izbor, zelena tvoj, ljubičasta agentov.",
  "Select makes the result on screen your pick.": "Izaberi čini rezultat na ekranu tvojim izborom.",
  "Copy image puts it on the clipboard, ready to paste as a reference.": "Kopiraj sliku je stavlja u klipbord, spremnu da se nalepi kao referenca.",
  Done: "Završeno",
  "Collect the finished assets": "Pokupi gotove asete",
  "Done is the shelf of approved assets. They are final: the agent uses these files and only makes variants of them.": "Završeno je polica odobrenih aseta. Oni su konačni: agent koristi te fajlove i od njih pravi samo varijante.",
  "Click a tile to see the asset full size. Click its name to copy it.": "Klikni pločicu da vidiš aset u punoj veličini. Klikni ime da ga kopiraš.",
  "This badge counts the variants the agent made from it: crops, sizes and formats.": "Ova oznaka broji varijante koje je agent napravio od njega: isečke, veličine i formate.",
  "Copy the image with one click.": "Kopiraj sliku jednim klikom.",
  "Details shows the whole history. Remove the approval there to reopen the slot, or clone it to try another direction.": "Detalji pokazuju celu istoriju. Tamo ukloni odobrenje da ponovo otvoriš slot, ili ga kloniraj da probaš drugi pravac.",
  "Good to know": "Dobro je znati",
  "That is the whole loop": "To je cela petlja",
  "Prompt, generate, review, approve. A few extras make long sessions easier.": "Prompt, generisanje, recenzija, odobrenje. Nekoliko dodataka olakšava duge sesije.",
  "The browser tab shows how many slots are still open, so the app can wait in the background.": "Tab u pregledaču pokazuje koliko je slotova još otvoreno, pa aplikacija može da čeka u pozadini.",
  "To change an approved asset, remove its approval in Details, or clone the slot and keep the original.": "Da promeniš odobren aset, ukloni mu odobrenje u Detaljima, ili kloniraj slot i zadrži original.",
  "Open this tour again any time with the Tutorial button in the top bar.": "Otvori ovaj vodič ponovo bilo kad dugmetom Vodič u gornjoj traci.",
  Agent: "Agent",
  "Writes the prompt": "Piše prompt",
  "One slot per asset, with the settings to use.": "Jedan slot po asetu, sa podešavanjima koja treba koristiti.",
  You: "Ti",
  "Generate it": "Generišeš",
  "In Google Flow or any other generator. Drop the result back.": "U Google Flow ili bilo kom drugom generatoru. Vraćaš rezultat.",
  "Agent · optional": "Agent · po želji",
  "Reviews the result": "Pregleda rezultat",
  "Only when you want its opinion. Recommends it, or writes the next version.": "Samo kad želiš njegovo mišljenje. Preporučuje ga, ili piše sledeću verziju.",
  "Any time, review or not. Your approval is final: the asset is done.": "Bilo kad, sa recenzijom ili bez nje. Tvoje odobrenje je konačno: aset je gotov.",
  "next version": "sledeća verzija",
  "Sees every result": "Vidi svaki rezultat",
  "Checks each one against its prompt.": "Proverava svaki prema promptu.",
  "Compares each image with its prompt and settings, and says what is off.": "Poredi svaku sliku sa promptom i podešavanjima i kaže šta ne valja.",
  "Understands video": "Razume video",
  "Judges a clip frame by frame.": "Ocenjuje klip frejm po frejm.",
  "Frame sheets, the first and last frame and a motion map let it judge a clip it cannot play.": "Tabla frejmova, prvi i poslednji frejm i mapa pokreta daju mu da oceni klip koji ne može da pusti.",
  "Has every final file": "Ima svaki finalni fajl",
  "Approved assets land in your project.": "Odobreni aseti stižu u tvoj projekat.",
  "Approved assets sit in the project folder, ready for the agent to use in its work.": "Odobreni aseti stoje u folderu projekta, spremni da ih agent koristi u radu.",
  "Makes variants": "Pravi varijante",
  "Crops, sizes and formats, no new run.": "Isečci, veličine i formati, bez novog generisanja.",
  "Crops, sizes and formats from the final asset, without another generation.": "Isečci, veličine i formati iz finalnog aseta, bez ponovnog generisanja.",
  "Any generator": "Bilo koji generator",
  "No MCP or API needed.": "Ne treba ni MCP ni API.",
  "Works with tools that have no MCP or API, such as Google Flow.": "Radi sa alatima koji nemaju ni MCP ni API, kao što je Google Flow.",
  "Costs less": "Košta manje",
  "Use the plan you already pay for.": "Koristi pretplatu koju već plaćaš.",
  "Generate on a plan you already pay for, instead of paying per API call.": "Generiši na pretplati koju već plaćaš, umesto da plaćaš po API pozivu.",
  Sound: "Zvuk",
  "A short beep when it is your turn again.": "Kratak zvuk kad si ponovo na potezu.",
  View: "Prikaz",
  "Page width, card density and tiles per row.": "Širina stranice, gustina kartica i broj pločica u redu.",
  "Copy a slot to try another direction.": "Kopiraj slot da probaš drugi pravac.",
  Undo: "Poništi",
  "Ctrl+Z brings back what you just removed, until your next change.": "Ctrl+Z vraća ono što si upravo uklonio, sve do sledeće promene.",
  Paste: "Nalepi",
  "Point at a card and press Ctrl+V.": "Pokaži na karticu i pritisni Ctrl+V.",
  "Open folder": "Otvori folder",
  "Every prompt and result is a plain file.": "Svaki prompt i rezultat je običan fajl.",
  "Tutorial, step {n} of {total}: {title}": "Vodič, korak {n} od {total}: {title}",
  "How Asset Prompter works": "Kako Asset Prompter radi",
  "Close the tutorial": "Zatvori vodič",
  'The app during the step "{title}"': "Aplikacija tokom koraka „{title}”",
  Steps: "Koraci",
  "{n}. {kicker}": "{n}. {kicker}",
  "Step {n}: {kicker}": "Korak {n}: {kicker}",
  Skip: "Preskoči",
  Back: "Nazad",
  "Start working": "Počni sa radom",

  // ---- Version ----
  "View full size": "Pogledaj u punoj veličini",
  "The agent will pick one, or choose it yourself": "Agent će izabrati jedan, ili ga izaberi sam",
  "{n} results": "Rezultata: {n}",
  "{n} results: pick one": "Rezultata: {n}, izaberi jedan",
  "{file} is the agent's pick; click to make it yours": "{file} je izbor agenta; klikni da bude tvoj",
  "{file} is your pick; click again to take it back": "{file} je tvoj izbor; klikni ponovo da ga povučeš",
  "Select {file}": "Izaberi {file}",
  "Drag this into the generator or a folder": "Prevuci ovo u generator ili folder",
  "Drag out": "Prevuci",
  Add: "Dodaj",
  "Add the image you copied in the generator": "Dodaj sliku koju si kopirao u generatoru",
  'Removed {file} from "{slot}" v{n}': "{file} je uklonjen iz „{slot}” v{n}",
  '{file} is back in "{slot}" v{n}': "{file} je vraćen u „{slot}” v{n}",
  "Waiting for {slots}": "Čeka na {slots}",
  "Generate this after that slot is approved: its result goes in as an input here.": "Generiši ovo kad taj slot bude odobren: njegov rezultat ovde ulazi kao ulaz.",
  "Generate this after those slots are approved: its result goes in as inputs here.": "Generiši ovo kad ti slotovi budu odobreni: njihovi rezultati ovde ulaze kao ulazi.",
  "Add a video anyway": "Ipak dodaj video",
  "Add an image anyway": "Ipak dodaj sliku",
  "Drop the video here": "Spusti video ovde",
  "Drop the image here": "Spusti sliku ovde",
  "or click to choose the downloaded file": "ili klikni da izabereš preuzeti fajl",
  "or click to choose a file, or press Ctrl+V while pointing at this card": "ili klikni da izabereš fajl, ili pritisni Ctrl+V dok pokazuješ na ovu karticu",
  "Choose video": "Izaberi video",
  "Paste image": "Nalepi sliku",
  "Drop into v{n}": "Spusti u v{n}",
  "Generate this in {name}": "Generiši ovo u alatu {name}",
  'Tool "{tool}" has no preset': "Alat „{tool}” nema preset",
  "Image or video": "Slika ili video",
  "Agent approves": "Agent odobrava",
  "Agent asked for another try: v{n}": "Agent traži još jedan pokušaj: v{n}",
  "Agent wants another try": "Agent želi još jedan pokušaj",
  "Agent review": "Recenzija agenta",
  "{title}, picks {file}": "{title}, bira {file}",
  "Your change request is waiting for the agent": "Tvoj zahtev za izmenu čeka agenta",
  "The agent left no note.": "Agent nije ostavio napomenu.",
  "Your change request is waiting for the agent.": "Tvoj zahtev za izmenu čeka agenta.",
  "{label} ({n})": "{label} ({n})",
  Input: "Ulaz",
  "View the {label}": "Pogledaj: {label}",
  "from {source} v{n}": "iz {source} v{n}",
  "from {source}": "iz {source}",
  "Not approved yet": "Još nije odobreno",
  "Change request sent to the agent": "Zahtev za izmenu je poslat agentu",
  "Change request removed": "Zahtev za izmenu je uklonjen",
  "Not saved yet. Saves when you click away, or press {key}.": "Još nije sačuvano. Čuva se kad klikneš van polja, ili pritisni {key}.",
  Saving: "Čuva se",
  Saved: "Sačuvano",
  Hide: "Sakrij",
  "Hide the change request": "Sakrij zahtev za izmenu",
  "What should change? The agent writes the next version from this result, its prompt and your request.": "Šta treba da se promeni? Agent piše sledeću verziju iz ovog rezultata, njegovog prompta i tvog zahteva.",
  "Prompt copied": "Prompt kopiran",
  "Already copied once; click to copy again": "Već jednom kopirano; klikni da kopiraš ponovo",
  "Copy the prompt for the generator": "Kopiraj prompt za generator",
  Copied: "Kopirano",
  "This version file has problems": "Fajl ove verzije ima probleme",
  "Doesn't match the settings": "Ne poklapa se sa podešavanjima",
  "Settings to check": "Proveri podešavanja",
  "Changed in v{n}": "Promenjeno u v{n}",
  "Show all": "Prikaži sve",
  "Approval removed": "Odobrenje uklonjeno",
  "Remove approval": "Ukloni odobrenje",
  "v{n} approved": "v{n} odobrena",
  "Approve v{n}": "Odobri v{n}",
  "Edit change request": "Izmeni zahtev za izmenu",
  "Request changes": "Traži izmene",
  "{n} variant": "{n} varijanta",
  "{n} variants": "{n} varijanti",

  // ---- ViewSettings ----
  "View settings": "Podešavanja prikaza",
  Width: "Širina",
  "Per row": "U redu",
  Density: "Gustina",
  Compact: "Zbijeno",
  "Applies to the Done grid.": "Važi za mrežu u Završeno.",
  "Applies to the slots in progress.": "Važi za slotove u toku.",

  // ---- lib ----
  "Request failed ({status})": "Zahtev nije uspeo ({status})",
  "This browser cannot read images from the clipboard. Point at the card and press Ctrl+V instead.": "Ovaj pregledač ne može da čita slike iz klipborda. Umesto toga pokaži na karticu i pritisni Ctrl+V.",
  "The browser blocked clipboard access. Allow it for this page, or point at the card and press Ctrl+V.": "Pregledač je blokirao pristup klipbordu. Dozvoli ga za ovu stranicu, ili pokaži na karticu i pritisni Ctrl+V.",
  "There is no image on the clipboard. Copy the image in the generator first.": "U klipbordu nema slike. Prvo kopiraj sliku u generatoru.",
  "This image could not be copied.": "Ova slika nije mogla da se kopira.",
  "{n} second ago": "pre {n} sekunde",
  "{n} seconds ago": "pre {n} sekundi",
  "{n} minute ago": "pre {n} minuta",
  "{n} minutes ago": "pre {n} minuta",
  "{n} hour ago": "pre {n} sata",
  "{n} hours ago": "pre {n} sati",
  "{n} day ago": "pre {n} dana",
  "{n} days ago": "pre {n} dana",
  "{n} month ago": "pre {n} meseca",
  "{n} months ago": "pre {n} meseci",
  "{n} year ago": "pre {n} godine",
  "{n} years ago": "pre {n} godina",
  "just now": "upravo sada",
  "Slot #{number}, created {when} ({ago})": "Slot #{number}, napravljen {when} ({ago})",

  // ---- main ----
  Loading: "Učitava se",
  "Result added to {slot} v{n}": "Rezultat dodat u {slot} v{n}",
  "{count} results added to {slot} v{n}": "Rezultata dodato u {slot} v{n}: {count}",
  "Point at the slot the pasted file belongs to, then paste again.": "Pokaži na slot kom nalepljeni fajl pripada, pa nalepi ponovo.",
  "Cannot reach the app server: {error}": "Server aplikacije nije dostupan: {error}",
  "Instructions for the agent copied": "Uputstvo za agenta je kopirano",
  "Copy agent instructions": "Uputstvo za agenta",
  "Show what gets copied": "Prikaži šta se kopira",
  "Open the project folder": "Otvori folder projekta",
  "How Asset Prompter works, step by step": "Kako Asset Prompter radi, korak po korak",
  Tutorial: "Vodič",
  "Sound on": "Zvuk uključen",
  "Sound off": "Zvuk isključen",
  Views: "Prikazi",
  "In progress": "U toku",
  "Deleted slots and results of this project": "Obrisani slotovi i rezultati ovog projekta",
  Trash: "Korpa",
  "Filter slots": "Filtriraj slotove",
  All: "Sve",
  "Agent notified": "Agent je obavešten",
  'The agent is not waiting right now. It gets this as soon as it starts waiting, or tell it "done" in the chat.': "Agent trenutno ne čeka. Dobiće ovo čim počne da čeka, ili mu napiši „gotovo” u razgovoru.",
  "The agent is waiting. Press to send it every slot where it is its turn, and what you approved since the last time.": "Agent čeka. Pritisni da mu pošalješ svaki slot gde je on na potezu, i šta si odobrio od prošlog puta.",
  "The agent is not waiting right now. It starts waiting after its turn, once it has read the new HOW-TO-USE.md.": "Agent trenutno ne čeka. Počinje da čeka posle svog poteza, kad pročita novi HOW-TO-USE.md.",
  "To send: {items}.": "Šalje se: {items}.",
  "{n} for the agent to work on": "{n} za agenta da obradi",
  "{n} approval to report": "{n} odobrenje da se javi",
  "{n} approvals to report": "{n} odobrenja da se jave",
  "Notify agent": "Obavesti agenta",
  "The agent stopped listening": "Agent je prestao da sluša",
  "Tell the waiting agent to stop listening. It starts again when you ask it in the chat.": "Kaži agentu koji čeka da prestane da sluša. Počinje ponovo kad ga zamoliš u razgovoru.",
  Stop: "Stani",
  "{n} slots approved": "Odobreno slotova: {n}",
  "Approve every slot the agent approved": "Odobri svaki slot koji je agent odobrio",
  "Approve all {n}": "Odobri sve ({n})",
  "A project is a folder. Your agent writes prompts into it, and you drop the generated images and videos back in.": "Projekat je folder. Tvoj agent u njega piše promptove, a ti u njega vraćaš generisane slike i video.",
  "No slots in {name} yet": "U projektu {name} još nema slotova",
  "Paste the agent instructions into your agent's chat and it will start writing prompts here. You can also write the first one yourself.": "Nalepi uputstvo za agenta u razgovor sa agentom i on će početi da piše promptove ovde. Prvi možeš da napišeš i sam.",
  "Nothing in progress. Approved assets are in Done.": "Ništa nije u toku. Odobreni aseti su u Završeno.",
  'Nothing here: no slot is "{status}".': "Ovde nema ničega: nijedan slot nije „{status}”.",
  "Nothing approved yet. Approved assets show up here.": "Još ništa nije odobreno. Odobreni aseti se pojavljuju ovde.",
  "ffmpeg is not installed, so videos get no frame sheets and an agent cannot review them.": "ffmpeg nije instaliran, pa video ne dobija table frejmova i agent ne može da ga pregleda.",
  "This version's release notes": "Beleške o ovoj verziji",
  "About Asset Prompter": "O Asset Prompteru",
  Website: "Sajt",
  "Report a problem": "Prijavi problem",
  "Runs on this machine only. Nothing leaves it but what you paste into your generator.": "Radi samo na ovom računaru. Ništa ga ne napušta osim onoga što sam nalepiš u generator.",
  "{n} variant of": "{n} varijanta od",
  "{n} variants of": "{n} varijanti od",
  "Variants of {name}": "Varijante: {name}",
  "Agent instructions": "Uputstvo za agenta",
  Copy: "Kopiraj",
  "Paste it into a new chat with your agent.": "Nalepi ga u nov razgovor sa svojim agentom.",
  "{name} is back": "{name} je vraćen",
  "{name} removed from the list": "{name} je uklonjen sa liste",
  "{name} moved to projects/_trash": "{name} je premešten u projects/_trash",
  "Trash of {name}": "Korpa projekta {name}",
  "Project added": "Projekat dodat",
  "Slot {name} created": "Slot {name} je napravljen",
  "v{n} saved": "v{n} sačuvana",
  "{from} copied to {to}, without approval": "{from} je kopiran u {to}, bez odobrenja",
  "{from} copied to {to}": "{from} je kopiran u {to}",
  "Undo (Ctrl+Z)": "Poništi (Ctrl+Z)",
  Dismiss: "Zatvori",

  // ---- version form ----
  Clear: "Obriši",
  "Any length from {min} to {max} seconds": "Bilo koje trajanje od {min} do {max} sekundi",
  "Settings in {name}": "Podešavanja u alatu {name}",
  "Generator settings": "Podešavanja generatora",

  Frames: "Frejmovi",
  "References ({n})": "Reference ({n})",

  // ---- shared ----
  "Copy slot name": "Kopiraj ime slota",
};

register("sr", SR);
